### Get all tourist places
GET http://localhost:8080/api/tourist

###

### Get places by category (Historical)
GET http://localhost:8080/api/tourist/category/Historical

###
GET http://localhost:8080/api/tourist/category/Nature


### Get places by rating (5 stars)
# GET http://localhost:8080/api/tourist/popularity_score

###


### Add a new tourist place
POST http://localhost:8080/api/tourist
Content-Type: application/json

{
  "name": "Golconda Fort",
  "location": "Hyderabad",
  "description": "Historic fort",
  "category": "Adventure"
}
