GET http://localhost:8080/vendor-api/vendors

###
GET http://localhost:8080/vendor-api/vendors/ram

###

POST http://localhost:8080/vendor-api/vendors
Content-Type: application/json


{
  "name":"lily",
  "city":"Hyderabad",
"area":"kphb",
"hygiene":{
   "total":25,
   "count":6,
   "avg":4.2
},
"overall":{
   "total":25,
   "count":6,
   "avg":4.2
},
"finalrating":4.2

}
###

POST http://localhost:8080/vendor-api/vendors
Content-Type: application/json



{
  "name":"ram",
  "city":"Hyderabad",
"area":"kphb",
"hygiene":{
   "total":25,
   "count":5,
   "avg":5
},
"overall":{
   "total":28,
   "count":7,
   "avg":4
},
"finalrating":4.5

}
###
POST http://localhost:8080/vendor-api/vendors
Content-Type: application/json


{
  "name":"jimin",
  "city":"Hyderabad",
"area":"kukatpally",
"hygiene":{
   "total":32,
   "count":8,
   "avg":4
},
"overall":{
   "total":40,
   "count":8,
   "avg":5
},
"finalrating":4.5

}
###

DELETE  http://localhost:8080/vendor-api/vendors/ram
###
POST  http://localhost:8080/vendor-api/vendors/2/newrating
Content-Type: application/json

{
   "newrating":5
}

###

POST  http://localhost:8080/vendor-api/vendors/r/newrating
Content-Type: application/json

{
   "newrating":3
}
###
POST  http://localhost:8080/vendor-api/vendors/ram/rating
Content-Type: application/json

{
   "hygienerating":4,
   "newrating":3
}